# Enables or disables the Rotating MOTDs plugin.
enabled: true

# The interval in seconds between each MOTD rotation.
intervalSeconds: 60

# The color code for the MOTDs.
motdsColor: "&c"

# The list of MOTDs to be rotated and displayed.
motds:
  - "Welcome to the server!"
  - "Have a great time playing!"
  - "Enjoy your stay!"
